<a href="https://colab.research.google.com/github/623020514-5/multivariate/blob/main/Funtion_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Function

In [2]:
def function_name(_Input_) :
        do_something with _input_ to get _Output_
        return _output_

SyntaxError: ignored

function มีส่วนสำคัญทั้งหมด 4 ส่วน
    
    1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)

    2. กำหนดตัวแปรที่จะเป็น Input (ขาดได้)

    3.ส่วนประมวลผล do_something with _input_ to get _Output_ (ขาดไม่ได้)

    4.ส่วน  _Output_return _output_ (ขาดได้)

In [ ]:
def print_name(name,surname,ID) :
        st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
        return st

In [ ]:
print_name('จุฑากาญจน์','ชิงจันทร์','623020514-5')

In [ ]:
output_string = print_name('จุฑากาญจน์','ชิงจันทร์','623020514-5')
print(output_string)

function ไม่จำเป็นต้องมี output

In [ ]:
def print_name2(name,surname,ID) : #ฟังก์ชั่นไม่จำเป็นต้องมี output
        st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
        print(st)

In [ ]:
print_name2('จุฑากาญจน์','ชิงจันทร์','623020514-5')

In [ ]:
op2 = print_name2('จุฑากาญจน์','ชิงจันทร์','623020514-5')

In [ ]:
print(op2)

function ไม่จำเป็นต้องมี input

In [ ]:
def Pi():
    return 3.14159265 

In [ ]:
#คำนวณพท.วงกลมที่มีเส้นผ่าศูนย์กลางเท่ากับ 3
Pi()*(1.5**2)

In [ ]:
def print_my_name():
    print('จุฑากาญจน์ 623020514-5')

In [ ]:
print_my_name()

In [ ]:
def print_2lines_default(name,surname,ID,grade='A'):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2 = f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)


In [ ]:
print_2lines_default('จุฑากาญจน์','ชิงจันทร์','623020514-5)

###Homework3 ให้เขียน Function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'15-49-44'

'00-00-16'

และ print ให้สวยงาม

###Answer

In [ ]:
def function_time(time):
    st = time.split('-')
    ans = int(st[0]) * 3600 + int(st[1]) * 60 + int(st[2]) 
    print(f'คำนวณจำนวนวินาทีจาก {time} จะเท่ากับ {ans} วินาที')

In [ ]:
function_time('14-15-31')

In [ ]:
function_time('13-00-01')

In [ ]:
function_time('15-49-44')

In [ ]:
function_time('00-00-16')

###No pandas

###Numpy

Numpy >>> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num + Py  >>> Number-Numerical + python

How to use to package

1```import``` ```ชื่อ package``` #เรียกใช้ package

2.```ชื่อ package.``` ```ชื่อ function```






data structure -> array

สร้าง array (numpy array)

In [4]:
import numpy

In [5]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [6]:
mat_ex1 [1,1] #[แถว,หลัก]

0.1

ถ้าไม่มี numpy array

In [3]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [7]:
list_ex1[1] 

[9.1, 0.1, 0.3]

In [8]:
list_ex1[1][1] #[แถว][หลัก]

0.1

In [9]:
print(list_ex1)
a= list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operation

data 2 แบบ -> matrix (2D array),scalar = ตัวเลขค่าคงที่

In [10]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


In [13]:
mat_ex3 = mat_ex1 + mat_ex2 #เอาตำแหน่งเดียวกันบวกหรือลบกันได้เลย และต้องมีมิติเท่ากัน
print(mat_ex3)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]


การตรวจสอบขนาดของ matrix 



```
.shape
```



In [14]:
mat_ex3.shape #จะเห็นว่าเป็น 2 มิติ

(2, 3)

In [15]:
mat_ex3.shape[0] #ใช้งานเหมือน list

2

## คูณ matrix

(หลักการคูณ คือ หลักเมตทริกตัวข้างหน้า ต้องเท่ากับแถวของเมตทริกตัวข้างหลัง)

dot product (ฟฟฟ,X)*(X,aaa)

In [16]:
print(mat_ex1)
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


In [17]:
mat_ex1 * mat_ex2

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

In [18]:
numpy.dot(mat_ex1,mat_ex2) #ต้องเช็ครูปร่างเมตทริค ถ้าอันนึง(2,3)อีกอันต้อง(3,2) 

ValueError: ignored

### Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว



```
Matrix.T
```



In [19]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [20]:
numpy.dot(mat_ex1,mat_ex2.T) #(2, 3).(3, 2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [21]:
numpy.dot(mat_ex1.T,mat_ex2)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

การบ้านครั้งที่ 4 

อธิบาย และใส่รูปการหา DEterminant และ Inverse matrix 